name: bach-mcp
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - libexpat=2.7.4
  - libffi=3.5.2
  - liblzma=5.8.2
  - libsqlite=3.51.2
  - libzlib=1.3.1
  - openssl=3.6.1
  - packaging=26.0
  - pip=26.0.1
  - python=3.11.14
  - setuptools=82.0.0
  - tk=8.6.13
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.46.3
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.81.0
      - anyio==4.12.1
      - asttokens==3.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - click==8.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - cryptography==46.0.5
      - debugpy==1.8.20
      - decorator==5.2.1
      - distro==1.9.0
      - docstring-parser==0.17.0
      - executing==2.2.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jiter==0.13.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - matplotlib-inline==0.2.1
      - mcp==1.26.0
      - nest-asyncio==1.6.0
      - parso==0.8.6
      - platformdirs==4.9.2
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - pure-eval==0.2.3
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.13.0
      - pygments==2.19.2
      - pyjwt==2.11.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.22
      - python-osc==1.9.3
      - pywin32==311
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rpds-py==0.30.0
      - six==1.17.0
      - sniffio==1.3.1
      - sse-starlette==3.2.0
      - stack-data==0.6.3
      - starlette==0.52.1
      - tornado==6.5.4
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.41.0
      - wcwidth==0.6.0
prefix: C:\Users\agust\anaconda3\envs\bach-mcp
